### PR TITLE
aync support and soap12 faults

### PR DESCRIPTION
**Pull request by sherpya**
you can review separately the two patches, I was unable to make two different pull requests sorry

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
@sherpya , you should make separate branch for each pull-request. Otherwise you'll get this mixed ups PRs.

I'm -1 for this PR. `pysimplesoap` is synchronous library. And this PR doesn't add full async functionality. It solves only your specific case, complicates entire library.

You can inherit you own class in your own scope from library's one and got the same functionality.

BTW, `concurrent.futures.ThreadPoolExecutor` makes every sync library "async-enough" and makes it in much safer way.

**Comment by sherpya** [comment]
yes but it does not make it usable with twisted, I mistitled the commit, it makes the lib transport agnostic not async, I use it in async way with twisted

**Comment by anton-ryzhov** [comment]
You are bringing extra complexity useless for everyone else. Your code still synchronous on receiving WSDL. This is not a solution, it's just dirty hack.

Use http://twistedmatrix.com/documents/8.2.0/api/twisted.python.threadpool.ThreadPool.html http://twistedmatrix.com/documents/13.2.0/core/howto/threading.html for synchronous libraries.

**Comment by sherpya** [comment]
maybe, I've borrowed the idea from  suds 0.4.1

**Comment by sherpya** [comment]
mixing urllib/curl with twisted network stack isn't a good idea either

**Pull request closed without merging**
