### PR TITLE
Fix for python3 and client controls soap version

### PR DESCRIPTION
**Pull request by sethcleveland**
- iteritems helper for python3 and python2

### CODE REVIEW

**Comment by reingart** [comment]
Hi @sethcleveland,   what has soap_ver to do with this patch?
Maybe you have to split this PR in two
Thanks for your collaboration!

**Comment by reingart** [comment]
BTW, please see PR #36

**Comment by anton-ryzhov** [comment]
I believe #36 fixes py3 better than this. This is trivial case, there is no helper function is required.

**Comment by reingart** [comment]
Seems duplicate of #36 an #58, closing due inactivity, please reopen if needed.

**Pull request closed without merging**
