### PR TITLE
Correctly check httplib2 version

### PR DESCRIPTION
**Pull request by bobpaw**
3 instances, supersedes #150 (sorry to @rtpg)

### CODE REVIEW

**Comment by ret2libc** [comment]
Hi, can this be merged into master? Are there any concern with this?

**Comment by bobpaw** [comment]
Looks like a few other people wrote an identical fix. Not sure why it hasn't been merged yet. I think I submitted a similar patch to Debian or something so that this one package was fixed (2 years ago so I don't really remember), but it hasn't been accepted yet here.

**Comment by ret2libc** [comment]
In fedora there is the same problem, but I was hoping upstream could accept the PR before patching our own version of the package as well.

**Comment by ret2libc** [comment]
ping @reingart is this project still maintained/alive?

**Comment by ret2libc** [comment]
ping n2 @reingart . I think I'm just going to include this fix in Fedora 32, even if not merged upstream.

**Comment by AyumuKasuga** [comment]
Thanks for merging the PR, but I think we also need to update version of the package and upload it to pypi.

**Comment by LiraelDianne** [comment]
Could we get a new version of this package uploaded to pypi to include this change please?

**Pull request merged**
